# Generated by Django 3.1.2 on 2020-10-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20190105_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='lat',
            field=models.FloatField(blank=True, default=0, help_text='Set to 0 to look up the lat, lng using geocoding. If the address is not found the zipcode will be used.'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lng',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
