# Generated by Django 2.1.1 on 2019-01-07 21:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_auto_20181115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='wishlist',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wishlists.WishList', verbose_name='Wish List'),
        ),
    ]
