# Generated by Django 2.1.1 on 2019-01-07 21:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20190105_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='classes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='classes', to='catalogue.ProductClass', verbose_name='Product Types'),
        ),
        migrations.AlterField(
            model_name='range',
            name='excluded_products',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='excludes', to='catalogue.Product', verbose_name='Excluded Products'),
        ),
        migrations.AlterField(
            model_name='range',
            name='included_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='includes', to='catalogue.Category', verbose_name='Included Categories'),
        ),
        migrations.AlterField(
            model_name='range',
            name='included_products',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='includes', through='offer.RangeProduct', to='catalogue.Product', verbose_name='Included Products'),
        ),
    ]
