# Generated by Django 2.1.5 on 2019-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20190107_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='catalogue.ProductClass', verbose_name='Product Types'),
        ),
        migrations.AlterField(
            model_name='range',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, related_name='excludes', to='catalogue.Product', verbose_name='Excluded Products'),
        ),
        migrations.AlterField(
            model_name='range',
            name='included_categories',
            field=models.ManyToManyField(blank=True, related_name='includes', to='catalogue.Category', verbose_name='Included Categories'),
        ),
        migrations.AlterField(
            model_name='range',
            name='included_products',
            field=models.ManyToManyField(blank=True, related_name='includes', through='offer.RangeProduct', to='catalogue.Product', verbose_name='Included Products'),
        ),
        migrations.AlterField(
            model_name='range',
            name='includes_all_products',
            field=models.BooleanField(default=False, help_text='If checked this will include every product except those in the excluded products list', verbose_name='Includes all products?'),
        ),
    ]
