# Generated by Django 2.2a1 on 2019-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_auto_20190110_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionaloffer',
            options={'ordering': ['-priority', 'pk'], 'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
    ]
