# Generated by Django 2.1.5 on 2019-01-28 16:20
import hashlib
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields

from oscar.core.loading import get_model


def get_wagtail_image(Image, image, title="Image"):
    with image.open() as f:
        file_hash = hashlib.sha1(f.read()).hexdigest()
    try:
        return Image.objects.get(file_hash=file_hash)
    except Image.DoesNotExist:
        img = Image(file=image, title=title, file_hash=file_hash)
        img.save()
        return img


def create_promo_images(apps, schema_editor):
    # Remove all option group links because the backend model changed
    PromoImage = apps.get_model('promotions', 'Image')
    Image = get_model('wagtailimages', 'Image')
    for promo_image in PromoImage.objects.all():
        if len(promo_image.original.name) > 99:
            promo_image.delete()  # Will create a DB error
            continue

        try:
            img = get_wagtail_image(
                Image,
                image=promo_image.original)
            promo_image.image_id = img.pk
            promo_image.save()
        except RuntimeError as e:
            if 'could not create decoder object' in str(e):
                promo_image.delete()
            else:
                raise
        except FileNotFoundError:
            promo_image.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'ordering': ('sort_order',), 'verbose_name': 'Ordered product', 'verbose_name_plural': 'Ordered product'},
        ),
        migrations.AlterModelOptions(
            name='orderedproductlist',
            options={'ordering': ('sort_order',), 'verbose_name': 'Ordered Product List', 'verbose_name_plural': 'Ordered Product Lists'},
        ),
        migrations.RenameField(
            model_name='keywordpromotion',
            old_name='display_order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='display_order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='orderedproductlist',
            old_name='display_order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='pagepromotion',
            old_name='display_order',
            new_name='sort_order',
        ),
        migrations.AlterField(
            model_name='keywordpromotion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproductlist',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pagepromotion',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='original'),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image'),
        ),
        migrations.RunPython(create_promo_images),
        migrations.RemoveField(
            model_name='image',
            name='original'
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='list',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.HandPickedProductList', verbose_name='List'),
        ),
        migrations.AlterField(
            model_name='orderedproductlist',
            name='tabbed_block',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='promotions.TabbedBlock', verbose_name='Tabbed Block'),
        ),
    ]
