# Generated by Django 2.2a1 on 2019-02-07 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20190128_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Promo Image', 'verbose_name_plural': 'Promo Image'},
        ),
        migrations.AlterModelOptions(
            name='multiimage',
            options={'verbose_name': 'Promo Image Set', 'verbose_name_plural': 'Promo Image Set'},
        ),
    ]
