# Generated by Django 2.2 on 2019-07-17 17:33

from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20190105_0023'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('shipping', '0003_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderanditemcharges',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is Enabled'),
        ),
        migrations.AddField(
            model_name='orderanditemcharges',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_shipping.orderanditemcharges_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='weightbased',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is Enabled'),
        ),
        migrations.AddField(
            model_name='weightbased',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_shipping.weightbased_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Slug')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('countries', models.ManyToManyField(blank=True, to='address.Country', verbose_name='Countries')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_shipping.method_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
