# Generated by Django 2.2 on 2019-07-17 23:17

from django.db import migrations, models
import django.db.models.deletion
from django.db import models, migrations


import oscar.models.fields.autoslugfield
from decimal import Decimal
import django.core.validators



class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20190717_1333'),
    ]

    operations = [
        # New
        migrations.RemoveField(
            model_name='orderanditemcharges',
            name='code',
        ),
        migrations.RemoveField(
            model_name='orderanditemcharges',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='orderanditemcharges',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderanditemcharges',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderanditemcharges',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='orderanditemcharges',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderanditemcharges',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='code',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weightbased',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='orderanditemcharges',
            name='method_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipping.Method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightbased',
            name='method_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shipping.Method'),
            preserve_default=False,
        ),
    ]
