# Generated by Django 2.2 on 2019-10-15 00:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_auto_20190724_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('user_agent', models.TextField(editable=False, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expiry_age', models.IntegerField(editable=False, null=True)),
                ('expiry_time', models.DateTimeField(editable=False, null=True)),
                ('time_on_site', models.IntegerField(editable=False, null=True)),
                ('end_time', models.DateTimeField(editable=False, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_time',),
                'permissions': (('visitor_log', 'Can view visitor'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(editable=False)),
                ('referer', models.TextField(editable=False, null=True)),
                ('query_string', models.TextField(editable=False, null=True)),
                ('method', models.CharField(max_length=20, null=True)),
                ('view_time', models.DateTimeField()),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.Visitor')),
            ],
            options={
                'ordering': ('-view_time',),
                'abstract': False,
            },
        ),
    ]
