# Generated by Django 2.2 on 2019-10-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_pageview_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('-expiry_time',), 'permissions': (('visitor_log', 'Can view visitor'),)},
        ),
    ]
