# Generated by Django 2.2.6 on 2019-10-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20191023_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='hostname',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
