# Generated by Django 2.1.1 on 2018-12-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('started', 'Checkout started'), ('payment-attempt', 'Payment attempt started'), ('payment-redirect', 'Redirected to payment processor'), ('payment-attempt', 'Payment attempt started'), ('payment-failed', 'Payment attempt failed'), ('payment-error', 'Payment error occurred'), ('error', 'Error occurred during checkout'), ('complete', 'Checkout and payment complete')], max_length=32)),
                ('data', models.TextField(verbose_name='Data')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_events', to='order.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Checkout Event',
                'abstract': False,
            },
        ),
    ]
