# Generated by Django 2.1.1 on 2019-01-07 21:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='order',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='order.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.Source', verbose_name='Source'),
        ),
    ]
