# Generated by Django 2.2.7 on 2020-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190107_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, help_text='Check number or Transaction ID', max_length=128, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, help_text='Status of the transaction (eg Deposited)', max_length=128, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(blank=True, choices=[('Authorize', 'Authorize'), ('Debit', 'Debit'), ('Refund', 'Refund')], max_length=128, verbose_name='Type'),
        ),
    ]
