# Generated by Django 2.1.1 on 2019-01-07 16:40

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_set',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='voucher.VoucherSet'),
        ),
        migrations.AlterField(
            model_name='voucherset',
            name='description',
            field=wagtail.core.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='voucherset',
            name='offer',
            field=modelcluster.fields.ParentalOneToOneField(blank=True, limit_choices_to={'offer_type': 'Voucher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_set', to='offer.ConditionalOffer', verbose_name='Offer'),
        ),
    ]
