# Generated by Django 2.1.1 on 2019-01-07 21:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_auto_20190107_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherapplication',
            name='voucher',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='voucher.Voucher', verbose_name='Voucher'),
        ),
    ]
