# Generated by Django 2.2a1 on 2019-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_auto_20190107_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherset',
            options={'get_latest_by': 'date_created', 'verbose_name': 'Voucher Set', 'verbose_name_plural': 'Voucher Sets'},
        ),
    ]
