# Generated by Django 2.1.1 on 2018-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20180914_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='shop_logo',
            field=models.ImageField(default='img/ui/image_not_found.jpg', max_length=255, upload_to='images/promotions/', verbose_name='Image'),
        ),
    ]
