# Generated by Django 2.2 on 2019-08-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190327_1505'),
        ('system', '0009_auto_20190812_1041'),
    ]

    operations = [
        migrations.RemoveField(model_name='configuration', name='shop_logo'),
        migrations.RemoveField(model_name='configuration', name='shop_logo_print'),
        migrations.AddField(
            model_name='configuration',
            name='shop_banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='shop_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='shop_logo_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
    ]
