# Generated by Django 2.2 on 2019-08-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190327_1505'),
        ('system', '0010_auto_20190812_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='shop_logo_alt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
    ]
