# Generated by Django 2.2 on 2019-08-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_configuration_shop_logo_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='shop_banner',
            field=models.ForeignKey(help_text='Banner imaged used by templates', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='shop_logo',
            field=models.ForeignKey(help_text='Logo used on light backgrounds', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='shop_logo_alt',
            field=models.ForeignKey(help_text='Logo used on dark backgrounds', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='shop_logo_print',
            field=models.ForeignKey(help_text='Logo used on print media', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='images.OscarImage'),
        ),
    ]
