# Generated by Django 2.2rc1 on 2019-03-25 16:48

from django.db import migrations


def migrate_images(apps, schema_editor):
    OscarImage = apps.get_model('images.OscarImage')
    WagtailImages = apps.get_model('wagtailimages', 'Image')

    for image in WagtailImages.objects.all():
        with image.file.open() as f:
            img = OscarImage(
                pk=image.pk,
                file=f,
                created_at=image.created_at,
                uploaded_by_user=image.uploaded_by_user,
                focal_point_x=image.focal_point_x,
                focal_point_y=image.focal_point_y,
                focal_point_width=image.focal_point_width,
                focal_point_height=image.focal_point_height,
            )
            img.save()
            #img.tags.add(image.tags)
            #img.save()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_images, migrations.RunPython.noop),
    ]
