# Generated by Django 2.2a1 on 2019-03-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sitepage',
            name='date',
        ),
    ]
