# Generated by Django 2.1.1 on 2018-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20181109_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date Created'),
        ),
    ]
