# Generated by Django 2.1.5 on 2019-01-10 22:40

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20181231_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='basket',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='basket.Basket', verbose_name='Basket'),
        ),
        migrations.AlterField(
            model_name='lineattribute',
            name='line',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='basket.Line', verbose_name='Line'),
        ),
    ]
