# Generated by Django 3.1.2 on 2020-10-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20190110_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineattribute',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True, verbose_name='Boolean'),
        ),
    ]
