# Generated by Django 3.1.5 on 2021-01-26 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0049_auto_20201002_1544'),
        ('basket', '0012_auto_20201002_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAttributeAddToCartOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.lineattribute')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.addtocartoption')),
            ],
            options={
                'verbose_name': 'Line attribute option',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lineattribute',
            name='value_multi_option',
        ),
        migrations.AddField(
            model_name='lineattribute',
            name='value_multi_option',
            field=models.ManyToManyField(blank=True, related_name='multi_valued_line_attribute_values', through='basket.LineAttributeAddToCartOption', to='catalogue.AddToCartOption', verbose_name='Value multi option'),
        ),
    ]
