# Generated by Django 2.1.1 on 2018-10-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20180911_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='If this is unchecked, this category will not be visible on the site.'),
        ),
    ]
