# Generated by Django 2.1.1 on 2019-01-07 21:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170429_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalogue.Product'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='review',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.ProductReview'),
        ),
    ]
