# Generated by Django 2.2.6 on 2019-11-06 16:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190327_1505'),
        ('reviews', '0005_auto_20190107_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-delta_votes', 'date_created'], 'verbose_name': 'Product review', 'verbose_name_plural': 'Product reviews'},
        ),
        migrations.AddField(
            model_name='productreview',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='images.OscarImage', verbose_name='Image')),
                ('review', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.ProductReview', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review image',
                'verbose_name_plural': 'Review images',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
